### ISSUE TITLE
你好，官方客户端有内存泄露的问题，这个docker镜像存在这个问题吗？

### ISSUE THREAD

**Issue by aipeach** [cmj2002/warp-docker#12]

**Comment by cmj2002** [comment]
我尚不清楚有关官方客户端内存泄露的信息。但是本项目基于官方客户端，它如果有内存泄漏的问题，本项目也会有。

一种缓解方法是在 `docker-compose.yml` 中限制容器的内存上限，这样占用的内存过多将导致容器自动重启。
