### ISSUE TITLE
当我在容器启动时候指定了外部network，流量代理就失效了。

### ISSUE THREAD

**Issue by beincy** [cmj2002/warp-docker#13]
在docker-compose.yml中，我添加了

networks:
  default:
    name: mynetwork
    external: true

mynetwork 是bridge
容器启动正常，warp状态也正常，只是做代理流量的时候失效了。抓了包，似乎握手都没有建立成功。

**Comment by cmj2002** [comment]
1080 端口上是否进行了端口映射？你所说的“握手”是指客户端无法连接到 warp 容器还是容器无法连接至网站？
