### ISSUE TITLE
最近忽然失效了

### ISSUE THREAD

**Issue by isunweihan** [cmj2002/warp-docker#14]
之前一直用着没问题，最近几天忽然发现用不了了。不需要翻墙网址还能打开，需要翻墙的不行了。

**Comment by cmj2002** [comment]
`curl --socks5 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace` 的输出如何？

根据反馈部分地区如果连不上 WARP 可能出现这种情况，可以试试宿主机能不能连上 WARP，如果不能就不是 warp-docker 的问题，我也无能为力。

**Comment by isunweihan** [comment]
容器内应该也是 WARP+，两个 TAG 的容器使用的配置是完全相同的，包括 WARP+ 的 Key。
有什么选项控制容器中使用的是 WARP or WARP+ 么？

**Comment by cmj2002** [comment]
由环境变量 `WARP_LICENSE_KEY` 控制，有的话就是 WARP+。切换的时候要删除 data 目录，如果它存在就不会重新注册，更改 key 也就无效。

**Comment by isunweihan** [comment]
`WARP_LICENSE_KEY` 这个两次都有配置，并且配置的是相同的，其他都没有修改，只是修改了镜像的 TAG。
周末我重新部署一个新的容器试一下。

**Comment by gzxiexl** [comment]
我更新镜像了也是不行了

**Comment by gzxiexl** [comment]
```
# curl --socks5 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace
fl=465f141
h=cloudflare.com
ip=240e:370:5b1c:7f70::1
ts=1706018283.332
visit_scheme=https
uag=curl/7.81.0
colo=SJC
sliver=none
http=http/2
loc=CN
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
# warp-cli account
Account type: Team
Device ID: 15df1c48-b9f7-11ee-b203-a60
Public key: a4c072d47034c5c5a0e11f05725a3a97abf3e33c8cf
Account ID: fb0201edb7e2e6cf37c2dd805
Organization: gzxiexl
# warp-cli connect
Success
# warp-cli status
Success
Status update: Disconnected. Reason: Manual Disconnection
# 
```

**Comment by gzxiexl** [comment]
日志反复出现如下：
```
stdout: [2m2024-01-23T14:03:13.414Z[0m [32m INFO[0m [2mwarp::warp_service::ipc_loop[0m[2m:[0m IPC: new connection [3mprivileged[0m[2m=[0mtrue [3mprocess_name[0m[2m=[0m"/usr/bin/warp-cli" [3mpid[0m[2m=[0m80
stdout: [2m2024-01-23T14:03:13.414Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc request: 7a1089f3-1464-447b-8148-a1a6014f2153; GetAppSettings
stdout: [2m2024-01-23T14:03:13.415Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc request: 6579fac1-aeb7-4acc-937a-bac4f03e264c; GetAccount
stdout: [2m2024-01-23T14:03:13.415Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc response: 6579fac1-aeb7-4acc-937a-bac4f03e264c; Registration: ID: t.15df1c48-b9f7-11ee-b203-a60c1d4b1c60; Public Key: a4c072d47034c5c5a0e11f05725a3a97abf3e33c8cf68aef5167c9158d7fa362; Managed: false; Account: Team { id: AccountId(fb0201ed-b7e2-e6cf-37c2-dd805ac11a66), managed: NotManaged, organization: "gzxiexl" };
stdout: [2m2024-01-23T14:03:13.416Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc request: 434811a7-62f8-4e89-8597-4cc8278f0bc1; GetDaemonStatus
stdout: [2m2024-01-23T14:03:13.416Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Sending IPC status update: Disconnected(Manual)
stdout: [2m2024-01-23T14:03:13.416Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc Broadcast ResponseStatus: Disconnected(Manual)
stdout: [2m2024-01-23T14:03:13.416Z[0m [34mDEBUG[0m [1mmain_loop[0m[2m:[0m [2mwarp::warp_service::ipc_handlers[0m[2m:[0m Ipc response: 434811a7-62f8-4e89-8597-4cc8278f0bc1; Success
stdout: [2m2024-01-23T14:03:13.417Z[0m [32m INFO[0m [2mwarp::warp_service::ipc_loop[0m[2m:[0m IPC connection ended
```

**Comment by cmj2002** [comment]
我无法在本地复现这个问题，所以无法进行诊断，网络上关于 `Manual Disconnection` 的信息也很少。 @gzxiexl  提供的日志也没有提供足以判断问题来源的信息。

由于我除了更新 warp 版本以外没有对镜像做任何修改，我只能假设这是新版本 warp 导致的问题，可以暂时回退到之前的版本。

**Comment by cmj2002** [comment]
我刚刚更新了容器中的 WARP 版本，新版本下您还会遇到此问题吗？

**Comment by zero-hero-he** [comment]
> 我使用TAG为`2023-07-18`的镜像可以，最新的不行了

同情况，最新版本不行，这个tag可用

**Comment by isunweihan** [comment]
尝试了最新版的，还是不行。之前版本依然可行。

**Comment by jeffreynet** [comment]
去年的老版本可用，升级到新版本就不行：
#warp-cli status                                             
Status update: Disconnected. Reason: Manual Disconnection                        
Success 
不知道为什么

**Comment by 1a57danc3** [comment]
> 尝试了最新版的，还是不行。之前版本依然可行。

https://github.com/go-gost/gost is next-gen gost.

**Comment by 1a57danc3** [comment]
In fact, there is no need to use gost.
https://developers.cloudflare.com/warp-client/get-started/linux/#switching-modes

```
warp-cli register
warp-cli set-mode proxy
warp-cli set-proxy-port 1080
warp-cli connect
warp-cli status
```

The socks port 1080 is warp listening port.

**Comment by cmj2002** [comment]
> In fact, there is no need to use gost. https://developers.cloudflare.com/warp-client/get-started/linux/#switching-modes
> 
> ```
> warp-cli register
> warp-cli set-mode proxy
> warp-cli set-proxy-port 1080
> warp-cli connect
> warp-cli status
> ```
> 
> The socks port 1080 is warp listening port.

If only using socks5, yes; but GOST allows us to use more features provided by GOST, such as more types of proxies, using port forwarding, etc., which can be achieved through the environment variable `GOST_ARGS`.

**Comment by htmambo** [comment]
今天docker日志中一直有dial tcp xxx.xxx.xxx.xx i/o timeout，不清楚啥原因

**Comment by 1a57danc3** [comment]
> 今天docker日志中一直有dial tcp xxx.xxx.xxx.xx i/o timeout，不清楚啥原因

If the website can be opened normally, It works.
This is normal.

**Comment by wodbzdysmmz** [comment]
2024-06-21 11:56:41 warp  | 2024-06-21T03:56:41.986Z DEBUG happy-eyeballs-diagnostics: warp::warp::connectivity_check: fl=22f364
2024-06-21 11:56:41 warp  | h=engage.cloudflareclient.com
2024-06-21 11:56:41 warp  | ip=2a09:bac1:3b60:10::16:16c
2024-06-21 11:56:41 warp  | ts=1718942202.202
2024-06-21 11:56:41 warp  | visit_scheme=https
2024-06-21 11:56:41 warp  | uag=
2024-06-21 11:56:41 warp  | colo=NRT
2024-06-21 11:56:41 warp  | sliver=none
2024-06-21 11:56:41 warp  | http=http/1.1
2024-06-21 11:56:41 warp  | loc=JP
2024-06-21 11:56:41 warp  | tls=TLSv1.3
2024-06-21 11:56:41 warp  | sni=plaintext
2024-06-21 11:56:41 warp  | warp=off
2024-06-21 11:56:41 warp  | gateway=off
2024-06-21 11:56:41 warp  | rbi=off
2024-06-21 11:56:41 warp  | kex=P-256
2024-06-21 11:56:41 warp  | 
2024-06-21 11:56:41 warp  | 2024-06-21T03:56:41.986Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: connectivity_check_result=Ok(TraceResult { metal_id: "22f364", colo: "NRT" }) ip=162.159.195.3
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.353Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: trace_result=Ok(TracerouteWrapper { traceroute: Traceroute { size: 72, src_ip: Some(11.8.2.1), dst_ip: Some(162.159.195.3), dst_name: "162.159.195.3", timestamp: 495, duration: 495, protocol: ICMP, max_ttl: Some(2), hops: [TraceHop { path_id: 1, ttl: 1, sent: 3, rcvd: 3, ip: Some(11.8.2.1), name: Some("11.8.2.1"), rtts: [0, 0, 0], errors: [] }, TraceHop { path_id: 1, ttl: 2, sent: 3, rcvd: 3, ip: Some(162.159.195.3), name: Some("162.159.195.3"), rtts: [163, 168, 163], errors: [] }], prelude_context: None, version: "2024.4.133", time_start: 2024-06-21 3:56:41.662693062 +00:00:00, time_end: 2024-06-21 3:56:42.158549785 +00:00:00 }, tunneled: false }) ip="162.159.195.3"
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.353Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: close time.busy=8.40ms time.idle=690ms
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Attempting Happy Eyeballs to 162.159.195.3:854 / [2606:4700:d1::a29f:c003]:854
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Start racer 11.8.2.17:60992 ---> 162.159.195.3:854
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::wireguard_tun: Handshaking wireguard with session tag affinity_tag=0
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: boringtun::noise: Sending handshake_initiation
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::wireguard_tun: Sent handshake initiation to 162.159.195.3:854
2024-06-21 11:56:42 warp  | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Happy Eyeballs check failed v6=[2606:4700:d1::a29f:c003]:854 err=UdpConnect(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" })
这是什么问题呢?

**Comment by cmj2002** [comment]
> 2024-06-21 11:56:41 warp | 2024-06-21T03:56:41.986Z DEBUG happy-eyeballs-diagnostics: warp::warp::connectivity_check: fl=22f364 2024-06-21 11:56:41 warp | h=engage.cloudflareclient.com 2024-06-21 11:56:41 warp | ip=2a09:bac1:3b60:10::16:16c 2024-06-21 11:56:41 warp | ts=1718942202.202 2024-06-21 11:56:41 warp | visit_scheme=https 2024-06-21 11:56:41 warp | uag= 2024-06-21 11:56:41 warp | colo=NRT 2024-06-21 11:56:41 warp | sliver=none 2024-06-21 11:56:41 warp | http=http/1.1 2024-06-21 11:56:41 warp | loc=JP 2024-06-21 11:56:41 warp | tls=TLSv1.3 2024-06-21 11:56:41 warp | sni=plaintext 2024-06-21 11:56:41 warp | warp=off 2024-06-21 11:56:41 warp | gateway=off 2024-06-21 11:56:41 warp | rbi=off 2024-06-21 11:56:41 warp | kex=P-256 2024-06-21 11:56:41 warp | 2024-06-21 11:56:41 warp | 2024-06-21T03:56:41.986Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: connectivity_check_result=Ok(TraceResult { metal_id: "22f364", colo: "NRT" }) ip=162.159.195.3 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.353Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: trace_result=Ok(TracerouteWrapper { traceroute: Traceroute { size: 72, src_ip: Some(11.8.2.1), dst_ip: Some(162.159.195.3), dst_name: "162.159.195.3", timestamp: 495, duration: 495, protocol: ICMP, max_ttl: Some(2), hops: [TraceHop { path_id: 1, ttl: 1, sent: 3, rcvd: 3, ip: Some(11.8.2.1), name: Some("11.8.2.1"), rtts: [0, 0, 0], errors: [] }, TraceHop { path_id: 1, ttl: 2, sent: 3, rcvd: 3, ip: Some(162.159.195.3), name: Some("162.159.195.3"), rtts: [163, 168, 163], errors: [] }], prelude_context: None, version: "2024.4.133", time_start: 2024-06-21 3:56:41.662693062 +00:00:00, time_end: 2024-06-21 3:56:42.158549785 +00:00:00 }, tunneled: false }) ip="162.159.195.3" 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.353Z DEBUG happy-eyeballs-diagnostics: warp::warp::tunnel::happy_eyeballs: close time.busy=8.40ms time.idle=690ms 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Attempting Happy Eyeballs to 162.159.195.3:854 / [2606:4700:d1::a29f:c003]:854 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Start racer 11.8.2.17:60992 ---> 162.159.195.3:854 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.656Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::wireguard_tun: Handshaking wireguard with session tag affinity_tag=0 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: boringtun::noise: Sending handshake_initiation 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::wireguard_tun: Sent handshake initiation to 162.159.195.3:854 2024-06-21 11:56:42 warp | 2024-06-21T03:56:42.657Z DEBUG main_loop:connect_inner{protocol="wireguard"}: warp::warp::tunnel::happy_eyeballs: Happy Eyeballs check failed v6=[2606:4700:d1::a29f:c003]:854 err=UdpConnect(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }) 这是什么问题呢?

你输入 License key 了吗，虽然 README 里面说是可选的，但是在中国大陆的多数地区免费账号是连不上的

**Comment by wodbzdysmmz** [comment]
一开始是没有,直接启动的.同样的问题.然后我去TG上生成了一个license key.然后镜像删除,更改配置文件.再次构建运行.依然提示Network is unreachable

**Comment by cmj2002** [comment]
> 一开始是没有,直接启动的.同样的问题.然后我去TG上生成了一个license key.然后镜像删除,更改配置文件.再次构建运行.依然提示Network is unreachable

主要是挂载的文件夹要删除，镜像倒是没必要重新构建。如果挂载的文件夹不删除，是不会更新账号信息的。

**Comment by wodbzdysmmz** [comment]
> > 一开始没有,直接启动的.同样的问题.然后我去TG上生成了一个许可证密钥.然后镜像删除,更改配置文件.再次构建运行.依然提示网络不可达
> 
> 主要是挂载的文件夹要删除，镜像倒是没必要重新构建。如果挂载的文件夹不删除，是不会更新账号信息。

有清空data目录.
![微信图片_20240625083332](https://github.com/cmj2002/warp-docker/assets/169221918/947b5563-48e6-44b3-b27c-0b377c3245f1)
> 删除镜像,重新启动依然如此

![微信截图_20240625083611](https://github.com/cmj2002/warp-docker/assets/169221918/d9ba3929-0471-4b86-a623-f33b2dd332e0)

**Comment by cmj2002** [comment]
> > > 一开始没有,直接启动的.同样的问题.然后我去TG上生成了一个许可证密钥.然后镜像删除,更改配置文件.再次构建运行.依然提示网络不可达
> > 
> > 
> > 主要是挂载的文件夹要删除，镜像倒是没必要重新构建。如果挂载的文件夹不删除，是不会更新账号信息。
> 
> 有清空data目录. ![微信图片_20240625083332](https://private-user-images.githubusercontent.com/169221918/342532389-947b5563-48e6-44b3-b27c-0b377c3245f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDgxNzEsIm5iZiI6MTcxOTQwNzg3MSwicGF0aCI6Ii8xNjkyMjE5MTgvMzQyNTMyMzg5LTk0N2I1NTYzLTQ4ZTYtNDRiMy1iMjdjLTBiMzc3YzMyNDVmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMzE3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzU5ZDExMzFmNjI5MmViOGJkMzlkMTZiNWI2N2E0NDY5ZTZlZGRhZDY0YTgyOGU4NDg3YjZlNzQ1M2E1NTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._3aj3t2DNF4xO4Mr5QY8BZE9npcNFebtZBj904rMFH4)
> 
> > 删除镜像,重新启动依然如此
> 
> ![微信截图_20240625083611](https://private-user-images.githubusercontent.com/169221918/342532374-d9ba3929-0471-4b86-a623-f33b2dd332e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDgxNzEsIm5iZiI6MTcxOTQwNzg3MSwicGF0aCI6Ii8xNjkyMjE5MTgvMzQyNTMyMzc0LWQ5YmEzOTI5LTA0NzEtNGI4Ni1hNjIzLWYzM2IyZGQzMzJlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMzE3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmFkMzUxMDg1ZjFiMzBhMDY4MTJhMjY2MWUyZDhiZDc0Yzk0Y2Y2YmU1N2ViZDI1ZjExNDk4MzUyNmI4OWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4ETZWGTTlBoJp4xWh6tVYawcFC1DV3IVvJt6YVd1IA)

在容器内运行 `warp-cli status` 返回什么呢？
