### ISSUE TITLE
无法远程连接socks5

### ISSUE THREAD

**Issue by ppoiissbsjksms** [cmj2002/warp-docker#15]
你好,搭建成功后运行curl --socks5 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace 回显warp=on正常
在其他主机使用这个socks5.提示无法连接curl: (28) Failed to connect to test.host.com port 9696 after 15461 ms: Couldn't connect to server
运行docker ps查看监听的是0.0.0.0
ce962203bbf2   caomingjun/warp   "/entrypoint.sh"         3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:9696->1080/tcp, :::9696->1080/tcp                                                      warp

**Comment by cmj2002** [comment]
防火墙是否放通了该端口？

**Comment by ppoiissbsjksms** [comment]
防火墙是放通的,tcping 9696端口失败.
我使用iptables转发7777端口至9696端口
curl --socks5 test.host.com:7777 https://cloudflare.com/cdn-cgi/trace
回显正常

**Comment by cmj2002** [comment]
> 防火墙是放通的,tcping 9696端口失败. 我使用iptables转发7777端口至9696端口 curl --socks5 test.host.com:7777 https://cloudflare.com/cdn-cgi/trace 回显正常

这样的话我认为不是容器的问题，应该还是某种防火墙问题。如果容器的 1080 端口直接绑定到主机的 7777 端口可用吗？

**Comment by ppoiissbsjksms** [comment]
请问是使用host模式吗?

**Comment by cmj2002** [comment]
不是，我指的是按照你原来的配置（默认应该是bridge模式），然后把9696改成7777

**Comment by Akimitsu333** [comment]
我遇到了类似问题。

socks5://127.0.0.1:1080 和 socks5://0.0.0.0:1080 都是可以正常访问的，但是 socks5://<服务器公网IP>:1080 访问超时。

我检查过 防火墙和运营商安全组，且调试后（nft flush ruleset）确定是容器的问题。

经过排查，问题根本原因在于 **容器内 cloudflare-warp nftables 默认 drop 入站公网流量**。

可通过如下方式修复：

```shell
docker exec -it -u 0 warp sh -c '
ip route replace a.a.a.a/32 via b.b.b.b dev eth0 table ccccc
nft insert rule inet cloudflare-warp input iifname "eth0" ip saddr a.a.a.a tcp dport 1080 accept
nft insert rule inet cloudflare-warp output oifname "eth0" ip daddr a.a.a.a tcp sport 1080 accept
'
```

其中，a.a.a.a 是 你访问服务器时用的客户端的IP，b.b.b.b 是 你warp容器的网关（例如我的是 172.21.0.1），ccccc 是 你warp容器内warp创建的自定义路由表表号（例如我的是 65743）。

关于 65743，可以用如下命令看到：

```shell
docker exec -it -u 0 warp sh -c 'ip rule'
```

输出应该类似：

```shell
0:	from all lookup local
32765:	not from all fwmark 0x100cf lookup 65743
32766:	from all lookup main
32767:	from all lookup default
```
