### ISSUE TITLE
可以支持Cloudflare Zero Trust吗？

### ISSUE THREAD

**Issue by hitsword** [cmj2002/warp-docker#18]

**Comment by cmj2002** [comment]
目前还不支持，但是技术上应该没问题。最近几天在写毕业论文，写完就更新一下启动脚本。

**Comment by cmj2002** [comment]
已经完成了更新。请按照[文档](https://github.com/cmj2002/warp-docker?tab=readme-ov-file#use-with-cloudflare-zero-trust)操作。
