### ISSUE TITLE
能否配合其他大佬的脚本进行每段时间后自动优选ip呢

### ISSUE THREAD

**Issue by labulac** [cmj2002/warp-docker#19]
感谢开源这么好用的docker
warp-cli 有这个设置自定义endpoint功能
```bash
warp-cli tunnel endpoint set <ENDPOINT>
```
能否配合其他大佬的脚本进行每段时间后自动优选ip呢？例如
https://gitlab.com/Misaka-blog/warp-script/-/raw/main/files/warp-yxip/warp-yxip.sh

优选ip对网速的提升有很大的效果

**Comment by cmj2002** [comment]
这个你把自动优选的脚本文件挂载进容器，在宿主机的 `cron` 任务里面加个 `docker exec <container_name> <path_to_script>` 就行了。

**Comment by labulac** [comment]
嗯嗯晚点我实现一下
