### ISSUE TITLE
Access warp-docker from remote

### ISSUE THREAD

**Issue by thelastblt** [cmj2002/warp-docker#27]
I'm trying to access warp-docker on a host machine from a remote machine. 

My firewall seems to allow 1080 but port scanning times out and I can't use the test curl from the remote machine using host ip. 

Is there any special setup with the container that I need to do to connect remotely? 

Goal: remote connect to host (running warp-docker) to route traffic through the container. 

For what it's worth everything works in docker/containers are able to access and use.

**Comment by cmj2002** [comment]
Is the test curl command success on host? We have another issue #23 that in some settings host cannot connect to container.

If it's success, the only possible reason is the firewall (assume you didn't change compose file and the connection between host and remote works fine). There are many firewalls you need to check, including the host's firewall (sometimes more than one), the VPS provider's firewall (usually set in their dashboard), and your local ISP may also block connections (especially when you are using your company's network or school's network).

**Comment by thelastblt** [comment]
Thank you! 

Yeah curl command in host works perfectly. Both as localhost and 127.0.0.1. Curl on host with its public ip times out. 

I'm running it on an Oracle VPS and swear my ports/firewall/network are set up right and I can see the container listening in the port. 

Maybe I'll try changing the port and see if that helps. Sounds like either way I'll have to troubleshoot there. Thank you!!

**Comment by thelastblt** [comment]
FYI, I chalked this up to a VPS/firewall issue.

Set up Tailscale and was able to access it across my devices.
