### ISSUE TITLE
cloudflare-warp 最新版支持MASQUE协议目前国内可用

### ISSUE THREAD

**Issue by gzxiexl** [cmj2002/warp-docker#29]
https://t.me/CF_NAT/38856
https://t.me/CF_NAT/38857
希望大佬有空添加支持下

**Comment by cmj2002** [comment]
这个在 zerotrust 控制面板上设置就好了，warp docker 这边应该不用做什么吧

**Comment by yangxiaobai945** [comment]
> 这个在 zerotrust 控制面板上设置就好了，warp docker 这边应该不用做什么吧
@gzxiexl 
[linux MASQUE](https://linux.do/t/topic/214128) 不会写Dockerfile 启动容器后手动编辑了下文件可以使用 @cmj2002 大佬看看能不能更新下dockerfile

**Comment by cmj2002** [comment]
哦你们是想在不用 zero trust 的情况下用 MASQUE 啊。 @yangxiaobai945  你发的文章我看了，应该不用改 dockerfile，映射一下 mdm 就好了，我晚上试试，没问题就写个简单的教程。

**Comment by yangxiaobai945** [comment]
> 哦你们是想在不用 zero trust 的情况下用 MASQUE 啊。 @yangxiaobai945 你发的文章我看了，应该不用改 dockerfile，映射一下 mdm 就好了，我晚上试试，没问题就写个简单的教程。

我怎么没想到映射文件呢😂

**Comment by cmj2002** [comment]
代码还是做了一点更改。之前的逻辑在有 MDM 的时候不会注册，因为之前 MDM 只和 zero trust 一起使用，会包含注册相关信息可以自动注册。

所以现在使用 MASQUE 的步骤就是
1. 下载 `enable_masque_mdm.xml`
2. 把 `docker-compose.yml` 里面的 `- REGISTER_WHEN_MDM_EXISTS=true` 和 `- ./enable_masque_mdm.xml:/var/lib/cloudflare-warp/mdm.xml` 取消注释
3. 启动容器

观察到似乎有 MDM 文件的时候 `warp-svc` 会慢一点，可以适当调高 `WARP_SLEEP`，比如调成 5，如果还是显示 daemon 没启动可以再调高。

**Comment by cmj2002** [comment]
Cloudflare 刚刚发布了新版本的 warp-cli，最新版镜像已经支持通过 `warp-cli tunnel protocol set MASQUE` 在 consumer version 上启用 MASQUE, 不再需要 `mdm.xml`
