### ISSUE TITLE
能否使用chatgpt-web重定向到wrap-docker来访问chatgpt?

### ISSUE THREAD

**Issue by padixa** [cmj2002/warp-docker#3]
比如在: [chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)的docker配置的proxy之类的地方设置该地址, 然后通过这个warp的网络来访问chatgpt?

**Comment by cmj2002** [comment]
我没用过 ChatGPT-Web，但是它的 README 有提到可以通过环境变量设置 SOCKS 代理，因此这种做法显然是可以的。

**Comment by padixa** [comment]
> 2023-09-13T16:07:55.684Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 20183968-566e-4e06-8452-5bc1a7ee0842; Error: Missing registration. Try running: warp-cli register
> Please accept the WARP Terms of Service by running this command in a TTY or by passing the --accept-tos flag.

启动遇到这种问题, 反反复复重启.

按你说的把:mdm.xml改成如下:(xx隐藏了)

<dict>
  <key>organization</key>
  <string>xx</string>  
  <key>auth_client_id</key>
  <string>fxx</string>
  <key>auth_client_secret</key>
  <string>xx</string>
</dict>

**Comment by cmj2002** [comment]
那你就按他说的加一个 `--accept-tos` 参数啊

**Comment by padixa** [comment]
你能否告诉我在docker-compose哪个地方加这个参数....

**Comment by cmj2002** [comment]
我猜测可能 Zero Trust 和 WARP/WARP+ 采用了不同的 TOS。我在镜像中已经 accept 过一次了，按道理不应该再问的。试试把[这一行](https://github.com/cmj2002/warp-docker/blob/df0f8b67dc2dd1589118c11ec5cd85b366126688/entrypoint.sh#L19)改成 `warp-cli --accept-tos register && echo "Warp client registered!"` 然后重新编译镜像。如果你不会的话等我明天起床再改代码编译。

**Comment by padixa** [comment]
那还是明天吧, 多谢. 我只是用了ZeroTrust, 然后加了个Service Tokens. 然后使用mdm.xml来填写那些内容. 其他没动.
