### ISSUE TITLE
podman启动后，socks无法通过公网IP访问

### ISSUE THREAD

**Issue by bamboox** [cmj2002/warp-docker#33]
telnet也不通 ， 但是 机器内网ip和127.0.0.1可以通
是和gost有关吗？

服务器再次通过gost 
gost-linux-amd64-2.11.5 -L socks5://user:pass@:3888   -F socks5://:1080

公网IP就能对外提供服务了，有点不理解

**Comment by cmj2002** [comment]
应该和 gost 无关，而是和 WARP 有关。如果不用容器直接运行 WARP 就是会导致公网 IP 无法访问。如果容器的网络不是 host 模式，猜测可能是 `--privileged` 或者映射 TUN 造成了隔离失效？

**Comment by bamboox** [comment]
> 应该和 gost 无关，而是和 WARP 有关。如果不用容器直接运行 WARP 就是会导致公网 IP 无法访问。如果容器的网络不是 host 模式，猜测可能是 `--privileged` 或者映射 TUN 造成了隔离失效？

docker run -p 80:80 nginx 

没有任何问题

**Comment by cmj2002** [comment]
我刚刚发那条信息的时候你还没改描述。根据你修改之后的描述，是 gost 暴露的端口无法通过公网 IP 访问？防火墙放通了吗？也有可能是 ISP 墙掉了 socks 连接？

另外要暴露到公网的话，我建议修改 GOST_ARGS 使用其他协议（基于安全的考虑，和此 issue 无关）

**Comment by bamboox** [comment]
> 我刚刚发那条信息的时候你还没改描述。根据你修改之后的描述，是 gost 暴露的端口无法通过公网 IP 访问？防火墙放通了吗？也有可能是 ISP 墙掉了 socks 连接？
> 
> 另外要暴露到公网的话，我建议修改 GOST_ARGS 使用其他协议（基于安全的考虑，和此 issue 无关）

端口，协议啥的都没有，我在用gost转一次就行，不过还有点其他问题，
再转一次
curl --socks5-hostname x:x@x.x.x.x:3888 https://cloudflare.com/cdn-cgi/trace 通
curl --socks5-hostname x:x@x.x.x.x:3888 https://chatgpt.com  不通
直接服务器上 
curl --socks5-hostname 127.0.0.1:1080 https://chatgpt.com  通

**Comment by cmj2002** [comment]
你所谓的 "curl --socks5-hostname x:[x@x.x.x.x](mailto:x@x.x.x.x):3888 https://cloudflare.com/cdn-cgi/trace 通" 显示了 `warp=on` 吗

**Comment by cmj2002** [comment]
这个我确实不太清楚，不过只要主机能够访问，容器的任务就完成了，公网 IP 无法访问应该是 Podman 或者防火墙的责任了。
