### ISSUE TITLE
is it possible to switch COLO location here?

### ISSUE THREAD

**Issue by utccnu** [cmj2002/warp-docker#35]
direct scenario here is, i need to connect to gemini api endpoint from an unsupported country(Spain, HK, etc), and cloudflare happens to offer colo in the same country, so no luck... is it possible to designate colo in warp?

**Comment by cmj2002** [comment]
No, at least not through the official client used by this project.

I recommend you buy a vps in a supported region (to run your application or to provide a proxy) to resolve this issue.
