### ISSUE TITLE
image for mikrotik arm64

### ISSUE THREAD

**Issue by amirmhs58** [cmj2002/warp-docker#36]
Dear Sir,

How should one proceed and what commands should be written to run this image in a MikroTik router container?

Kind Regards,
Amir

**Comment by cmj2002** [comment]
[The image supports arm64 (armv8)](https://github.com/cmj2002/warp-docker/issues/8), so you should be able to proceed according to the instructions in the README. If you encounter any errors, please provide the relevant output.

**Comment by amirmhs58** [comment]
I spent several hours but could not run this Docker correctly on Mikrotik. I got tired and gave it up. If anyone has experience with this particular case and can explain it would be great.

**Comment by inean** [comment]
MikroTik doesn't allow to use cap_add NET_ADMIN on containers, so this won't work. You must side load image on a container in your local network and forward requests to it
