### ISSUE TITLE
[request] disable qlog for prevent huge log file

### ISSUE THREAD

**Issue by ukari** [cmj2002/warp-docker#38]
[what are the qlogs and a report of qlog file size problem](https://www.reddit.com/r/CloudFlare/comments/1g6h9rt/what_are_qlogs/)

use this `warp-cli debug qlog disable` could disable qlog

**Comment by cmj2002** [comment]
Disable qlog by default, user can enable it by passing `DEBUG_ENABLE_QLOG`.
