### ISSUE TITLE
是否支持 warp-connector？

### ISSUE THREAD

**Issue by SuperNG6** [cmj2002/warp-docker#39]
您好，感谢制作这么好的镜像，想请教一下，是否支持warp-connector？我想在几台VPS之间组内网。目前没有在说明中看到相关的配置选项（无`WARP Connector with token`配置）
https://blog.cloudflare.com/zh-tw/introducing-warp-connector-paving-the-path-to-any-to-any-connectivity-2/

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/28b8c2ee-9f56-4b4b-908f-d2c8ee7c5390">

**Comment by cmj2002** [comment]
支持的，在文档中有: https://github.com/cmj2002/warp-docker/blob/main/docs/warp-connector.md
