### ISSUE TITLE
 daemon is not running

### ISSUE THREAD

**Issue by morkvk** [cmj2002/warp-docker#42]
at some point, I started making a mistake:

`Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)`
`Maybe the daemon is not running?`
`2024-12-08T07:40:54.047Z  INFO warp::warp_service: Starting WarpService pid=15`
`2024-12-08T07:40:54.048Z  INFO warp::warp_service: Version: 2024.11.309.0`

**Comment by cmj2002** [comment]
Try increasing the `WARP_SLEEP`. Default is `2` (2 seconds). `warp-svc` may take longer time to start on some device.

**Comment by morkvk** [comment]
It looks like it's working 
thanks!
