### ISSUE TITLE
Problems when deploying in docker swarm

### ISSUE THREAD

**Issue by yourichng** [cmj2002/warp-docker#43]
I was orchestrating multiple warp clients using docker swarm.

However, I recently encountered a problem and checked to see that the issue was caused by a containerd update. After adding the same two lines to the docker-compose.yml file,

```
devices:
  - /dev/net/tun:/dev/net/tun
```

and running it, I still get tun-related errors and

I was redirected to this link:

https://github.com/cmj2002/warp-docker/blob/main/docs/tun-not-permitted.md

I checked that devices are not activated in swarm. Is there a way to use this problem without updating?

![스크린샷 2024-12-09 오후 4 32 16](https://github.com/user-attachments/assets/c8c4c330-ae23-4353-9224-16e8bf791f02)

**Comment by cmj2002** [comment]
I'm not familiar with Docker Swarm. What do you mean by "devices are not activated in swarm"? Are you saying that there is no `/dev/net/tun` device on the host machine of the swarm, or that Swarm does not support passing TUN device?

**Comment by yourichng** [comment]
My guess is that Swarm does not support passing TUN device.

**Comment by yourichng** [comment]
```docker-compose.yml
services:
  warp:
    image: caomingjun/warp:latest
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always
    ports:
      - '1080:1080'
    environment:
      - GOST_ARGS=-L :1080
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    deploy:
      mode: replicated
      replicas: 30
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
```

It is a docker-compose.yml file, and when deploying, it was deployed through

```bash
docker stack deploy -c ./docker-compose.yml warp
```

**Comment by cmj2002** [comment]
My guesses is that perhaps with both mapping device and creating TUN in the container, container in swarm will be able to access it. To do this, I will add legacy tun support to the container, but I don't know how to use swarm and may need your help for testing later.

**Comment by yourichng** [comment]
thank you.

**Comment by cmj2002** [comment]
Can you pull the latest image and pass env `LEGACY_TUN_SUPPORT=true` to test it?

**Comment by yourichng** [comment]
It seems to work fine in swarm.

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/13dd054c-b676-454e-8c30-9a4528c29a31">

**Comment by yourichng** [comment]
Sorry for the confusion.

First of all, I rolled back the service instance to the old version,

and the same problem occurred the moment I updated containerd.

**Comment by cmj2002** [comment]
Have you already:
- Updated to the latest version of warp-docker
- Passed the TUN device (although swarm cannot truly pass TUN device, this will solve new `containerd` restrictions on device access)
- Set LEGACY_TUN_SUPPORT=true

And still failed under these circumstances? What is the output?

**Comment by yourichng** [comment]
installed version

- containerd.io: 1.7.24-3.1.el9
- docker-buildx-plugin: 0.19.2-1.el9
- docker-ce: 3:27.4.0-1.el9
- docker-ce-cli: 1:27.4.0-1.el9
- docker-compose-plugin: 2.31.0-1.el9

$ docker stack deploy -c docker-compose.yml warp
```
Ignoring unsupported options: devices
```

```
ERROR main_loop: warp::warp_service: Connection error error=IoError(AnnotatedIoError { err: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }, context: "open tun" })
```

**Comment by cmj2002** [comment]
There is nothing I can do in this case, you can open an issue in containerd or swarm to ask containerd to revert the change or swarm to support passing tun.
