### ISSUE TITLE
docker部署，team帐户，持久化，删除容器后，重新部署无法启动

### ISSUE THREAD

**Issue by zshawk** [cmj2002/warp-docker#44]
部署后，我切换成了team帐户，数据持久化后，删除容器后再次部署时，entrypoint.sh脚本执行到`warp-cli debug qlog disable`需要同意隐私政策`Accept Terms of Service and Privacy Policy? [y/N]`，会导致后面的gost命令无法执行

**Comment by zshawk** [comment]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/cf6e5755-e3af-44f4-a849-3d31cba2f6ee">
<img width="453" alt="image" src="https://github.com/user-attachments/assets/922870f6-1e6e-4c8d-a604-3c4264107684">
docker-compose.yaml中增加`tty: true`，`entrypoint.sh` 脚本中的 `warp-cli debug qlog disable` 前面增加 `yes`，目前我按照这种方式，team帐户第二次可以正常启动

**Comment by cmj2002** [comment]
如果把命令改成 `warp-cli --accept-tos debug qlog enable` 和 `warp-cli --accept-tos debug qlog disable` 呢？

**Comment by zshawk** [comment]
<img width="423" alt="image" src="https://github.com/user-attachments/assets/e6604a7b-6768-4bc4-8670-0b1fd9f48930">

命令中增加 `--accept-tos` 参数确实可以了，也不用加 `tty: true`，原来还有这样的参数，我不太了解，非常感谢
