### ISSUE TITLE
i cann't run it on my OpenWRT

### ISSUE THREAD

**Issue by FuDujilm** [cmj2002/warp-docker#45]
logs:
![image](https://github.com/user-attachments/assets/73e37ee2-c8cf-43ca-a47a-676955d889c9)
> warp  | 2024-12-13T16:12:24.208Z  INFO warp::warp_service: Starting WarpService pid=15
warp  | 2024-12-13T16:12:24.208Z  INFO warp::warp_service: Version: 2024.11.309.0
warp  | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
warp  | 
warp  | Maybe the daemon is not running?
warp  | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
warp  | 
warp  | Maybe the daemon is not running?
warp exited with code 1

**Comment by cmj2002** [comment]
Try increasing the `WARP_SLEEP`. Default is `2` (2 seconds). `warp-svc` may take longer time to start on some device.
