### ISSUE TITLE
Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by msTokens** [cmj2002/warp-docker#46]
warp23y  | 2024-12-14T23:26:15.632Z  INFO warp::warp_service: Starting WarpService pid=16
warp23y  | 2024-12-14T23:26:15.632Z  INFO warp::warp_service: Version: 2024.11.309.0
warp23y  | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
warp23y  | 
warp23y  | Maybe the daemon is not running?
warp23y  | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
warp23y  | 
warp23y  | Maybe the daemon is not running?
warp23y exited with code 1

**Comment by msTokens** [comment]
i added TUN to device, but under latest docker and latest containerd i get this when i start the container :) how to fix it?

**Comment by cmj2002** [comment]
Try increasing the `WARP_SLEEP`. Default is `2` (2 seconds). `warp-svc` may take longer time to start on some device.

In addition, I recommend that you update to the latest image and use the new solution in the [documentation](https://github.com/cmj2002/warp-docker/blob/main/docs/tun-not-permitted.md). The previous TUN passing solution seemed to cause issues on platforms like Docker Swarm, so we have changed to another solution that no longer requires TUN passing but does require adding `device_cgroup_rules`.
