### ISSUE TITLE
warp-cli status always manual disconnection

### ISSUE THREAD

**Issue by cakriwut** [cmj2002/warp-docker#9]
Hi,
I tried to use this docker, but it doesnt seems working. I have successfully register the device, however when I check with warp-cli status, it always showing the warp is off.

```
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
```

Can anyone help me?

**Comment by cmj2002** [comment]
If Docker is not used, can WARP be used in the host machine's network environment? It is possible that your company or local ISP is blocking the WARP connection. If the host machine can connect but Docker cannot, please provide more detailed logs for diagnosis.
